### ISSUE TITLE
Bill payment, banking 

### ISSUE THREAD

**Issue by sparcoxalpha** [DmACKGL/GCPhone-Rewritten#46]
Unpaid bill can pay through phone
Check bank balance, transfer, transfer history etc

**Comment by DmACKGL** [comment]
Hey @sparcoxalpha!

This feature is on my internal roadmap, ETA: next week (if everything is ok)

**Comment by sparcoxalpha** [comment]
Valet option also is there means good,and camera without screenshot basics

**Comment by sparcoxalpha** [comment]
Notification sound not working.. please help
