### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TaaVetP** [DmACKGL/GCPhone-Rewritten#56]
**Describe the bug**
Unable to send messages or receive messages

**To Reproduce**
I just try to send message but it doesnt send it and gives me error

**Expected behavior**
I expected the message to be sent

**Screenshots**
https://gyazo.com/dace22634e9d2aa2fa3a8a64d25191c5

**FiVEM(please complete the following information):**
 I use mumble-voip and the newest artifact

**Additional context**
--

**Comment by DmACKGL** [comment]
Duplicated #45. I'll discuss the issue there, thanks for the issue!
