### ISSUE TITLE
UI bug[BUG]

### ISSUE THREAD

**Issue by alanjo4** [DmACKGL/GCPhone-Rewritten#6]
**Describe the bug**
Hi guys how you doing? I get some UI errors (IN-GAME) after try the npm run build command, Looks like the bundle is not correct or (also a possibility) I'm doing something bad in the build process. Have a good day guys!

**To Reproduce**
1. Build the project
2. Use HTML folder in your fivem server
3. Try to open contacts or something like that
4. Press F8 and see those javavascript errors.

**Expected behavior**
The UI should render in the phone

**Screenshots**
![image](https://user-images.githubusercontent.com/25183741/111922455-9b3b5e80-8a78-11eb-8f11-7def2d2a60ad.png)

**Additional context**
No more additional context

**Comment by DmACKGL** [comment]
Hey!

Can you try this build? https://github.com/DmACKGL/GCPhone-Rewritten/suites/2310042444/artifacts/48487319
It's from https://github.com/DmACKGL/GCPhone-Rewritten/commit/8e181902e45e05ed6f1637bbd0b16fea4df13c02

**Comment by DmACKGL** [comment]
Also, I recommend using Yarn (https://yarnpkg.com/) instead of NPM due to package locks.

**Comment by alanjo4** [comment]
Thanks for the recommendation! I still seeing the same issue:
![image](https://user-images.githubusercontent.com/25183741/111928093-70a9cf80-8a91-11eb-86ae-46e7e51275af.png)

Very weird. Probably some error when Vue try to populate the contact. What I'm trying to say is something like this:

```
let somethingThatIsSupposedToBeAnArray;

function populateContacts() {
    somethingThatIsSupposedToBeAnArray.length //Error here
}
```

**Comment by alanjo4** [comment]
Another curious thing that I just realized, is when I build the version (I tried yarn this time), my html page is full white, like there is no vue app there, like this:

![image](https://user-images.githubusercontent.com/25183741/111929321-caf85f80-8a94-11eb-88c3-dc00504377eb.png)

There weren't errors in the dev process. Have a nice week bro!

**Comment by DmACKGL** [comment]
Hey!

Change this variable to True https://github.com/DmACKGL/GCPhone-Rewritten/blob/8e181902e45e05ed6f1637bbd0b16fea4df13c02/src_htmlPhone/src/App.vue#L48

Remember to change it to false before building the app.

**Comment by alanjo4** [comment]
Hey! Yes, I import all SQL files to my DB. The problem appears when I go to the contact module. So I suppose this problem can be related to when vue tries to fill the contact list, probably in the Parameter.vue? I don't know, I'm a C++ developer, a newbie in this world of scripting but I did some jobs with react. So if you want to create other interesting things, just let me know, I'm from Argentina, and as I saw, you're from Chile. But anyway, let's keep this thread in English because the majority of ESX users are English speakers (likely).

PS: I can create clear documentation because as you probably know, ESX documentation tends to be a piece of ... When you start in this world, you should go to the code and the code is your documentation, it's you and the code, and probably a little useless documentation help. My discord is alanjo#2556.

**Comment by DmACKGL** [comment]
I'll try to replicate the BUG later today.

**Comment by alanjo4** [comment]
Hi bro, don't waste your time, I just solved this problem. I'll explain what going on:

1) If you installed other versions of gcphone you'll have problems even if the author says that you will not have problems if you have other gcphone before.

2) Removes ALL tables and Columns created by other gcphones.

3) Create tables and column with the correspondent GCphone .sql files (this version)

Enjoy it!

**Comment by DmACKGL** [comment]
Good to hear!
Don't worry; all issues are welcome.
