### ISSUE TITLE
[BUG] Contact UI

### ISSUE THREAD

**Issue by alanjo4** [DmACKGL/GCPhone-Rewritten#7]
**Describe the bug**
UI interface is bug when "create a new contact"

**To Reproduce**
1. Go to Menu
2. Click on Contact
3. Click on "New Contact"
3. See the bug

**Expected behavior**
Input and labels should render with a friendly space between them

**Screenshots**
![image](https://user-images.githubusercontent.com/25183741/112018723-996faa80-8b0d-11eb-83b1-895ab53c3ad5.png)

**Additional context**
The problem should be solved after remove "absolute" value for position property in:
![image](https://user-images.githubusercontent.com/25183741/112018963-c58b2b80-8b0d-11eb-8ee9-d2db9f62c0ea.png)

But I don't know if you use the same CSS identifier for other components. After removing absolute:
![image](https://user-images.githubusercontent.com/25183741/112019160-ee132580-8b0d-11eb-9c3b-a421222889cb.png)

**Comment by DmACKGL** [comment]
Fixed on #8
